DOT PRODUCT WITH NUMPY

The NumPy dot product in Python is a fundamental mathematical operation used for multiplying arrays or matrices efficiently. It calculates the sum of the element-wise products of two arrays. 


Mathematically; Dot product is also scalar product and it’s a measure of how closely two vectors align in terms of direction.
Dot product formula; This can be denoted either algebraically or geometrically	
Geometrically; The geometric meaning of dot product is that the dot product between two given vectors a and b is denoted by: a.b= |a||b|cosθ
Algebraically; The dot product algebra says that the dot product of the given two products
 a = (a1, a2, a3) and b= (b1, b2, b3) is given by: a.b= (a1b1 + a2b2 + a3b3)


PROPERTIES OF THE DOT PRODUCT

Commutative Property; For any two vectors x and y, x.y= y.x
Scalar Multiplication Property; For any two vectors a and b and any real number z, (za).b = a.(zy) = z(x.y) or  ab(x.y)=(ax.by)

Distributive Property; For any 3 vectors a, b and c, a.(b+c) = a.b + a.c

Orthogonal Property; Two vectors are orthogonal only when a.b = 0

In [3]:
# If both a and b are 1-D arrays, it is inner product of vectors 
# (without complex conjugation).
# Neither argument is complex-conjugated:
import numpy as np 
#  returns the dot product of vectors a and b. It can handle 2D arrays but considers them as 
# matrix and will perform matrix multiplication

# dot product of two scalars
x=3
y=4
print(np.dot(x, y))

a=np.dot(6,12)
print(a)
# Considering two complex numbers
a = [2+6j]
b = [4+3j]
print(np.dot(a, b ))
#normally; 2(4+3j) + 6j(4+3j)= 8+6j+24j-18= -10+30j
# note; As we write complex numbers we begin with the real part followed by the imaginary part
# -10 is the real part and 30j is the imaginary part
# j*j=-1

print(np.dot([2j, 3j], [5j, 8j]))
print(np.dot([2+3j, 5+6j], [9+7j, 4+12j]))

ModuleNotFoundError: No module named 'numpy'

In [4]:
# getting the dot product of 1-D arrays
x = np.array([5, 1, 3, 2])
y = np.array([6, 4, 9, 4])
print(np.dot(x,y))
# normally it would be 5*6+1*4+3*9+2*4=69

# example 2
a= [2,4,6]
b= [5,7,9]
print(np.dot(a,b))

a = 3+1j 
b = 7+6j
print(np.dot(a,b))

NameError: name 'np' is not defined

In [5]:
arr=np.array([3,1,9,7])
arr1=np.array([2,6,4,8])
print(np.dot(arr,arr1))

NameError: name 'np' is not defined

In [30]:
# If both a and b are 2-D arrays, it is matrix multiplication, but 
# using matmul or a @ b is preferred.
# For 2-D it's a matrix product
import numpy as np
a = np.array([[1, 5], [0, 1]])
b = np.array([[4, 3], [-2, -1]])
np.dot(a, b)

a=np.array([[3,1],[2,4]])
b=np.array([[5,2],[1,6]])
c=np.dot(a,b)

In [24]:
# 2-D matrix
a = np.array([[1, 5], [0, 1],[4,5]])
b = np.array([[4, 3], [-2, -1],])
np.dot(a,b)

array([[-6, -2],
       [-2, -1],
       [ 6,  7]])

In [32]:
# 2-D matrix
x=[[1,2],[4,1]]
y=[[4,11],[2,3]]
z=np.dot(x,y)
print(z)

[[ 8 17]
 [18 47]]


In [34]:
a=[[1,0],[0,1]]
b=[[4,1],[2,2]]
c=np.dot(a,b)
print(c)

[[4 1]
 [2 2]]


REFERENCES

https://numpy.org/doc/stable/reference/generated/np.dot.html

G. H. Golub and C. F. Van Loan, Matrix Computations, 3rd ed., Baltimore, MD, Johns Hopkins University Press, 1996, pg. 8.

Alon.B.Muhame (How to use numpy library)

linear-guest.pdf