In [1]:
#EXAMPLE 1
import numpy as np

# Create a NumPy array (vector)
vector = np.array([1, 2, 3, 4, 5])

# Adding a scalar to the vector
scalar = 10
result = vector + scalar

print(result)


[11 12 13 14 15]


In [11]:
#EXAMPLE 2
import numpy as np

# Create a NumPy array (vector)
vector = np.array([5, 10, 15, 20, 25])

# Add a scalar to the vector
scalar = 7
result = vector + scalar

#print("Original Vector:")
#print(vector)

print(result)  #print("\nResult after adding the scalar:")


[12 17 22 27 32]


In [10]:
#EXAMPLE 3
import numpy as np
#creating a numpy array 
vector = np.array([2,10,20,25,30])

# we then add a scalar to a vector
scalar = 8
result = vector + scalar

print (vector)
#print("original vector:")

print(result)


[ 2 10 20 25 30]

Result after adding the scalar:
[10 18 28 33 38]


REFERENCES
https://www.w3resource.com/python-exercises/python-functions-exercise-2.php