QUESTION

#MATRIX, DETERMINANT AND VECTOR TRANSFORMATION MANIPULATION WITH NUMPY.

GROUP 2:

MEMBERS:                                REG.NO

ALOYO BRENDA                            2023/DCSE/009/SS
AMESO IMMACULATE                        2023/DCSE/0010/SS
NANZIRI RITAH NAMAYANJA                 2023/DCSE/0082/SS
NALUBEGA JOAN                           2023/DCSE/0102/SS
NAKANJAKO JOSEPHINE                     2023/DCSE/0060/SS
TIBAWALA SHARON                         #DIDNT DO THE WORK, DIDNT COMMUNICATE.
NAMAKULA ALLEN                          2023/DCSE/0069/SS


In [10]:
#MATRIX ADDITION
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.add(matrix1, matrix2)
print(result)

[[ 6  8]
 [10 12]]


In [11]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = matrix1 + matrix2
print(result)

[[ 6  8]
 [10 12]]


In [12]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.add(matrix1, matrix2, out=np.empty_like(matrix1))
print(result)

[[ 6  8]
 [10 12]]


In [24]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.zeros_like(matrix1)
np.add(matrix1, matrix2, out=result)
print(result)

[[ 6  8]
 [10 12]]


MATRIX MULTLPICATION

In [9]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [5]:
import numpy as np

# Define matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Print the result
print(result)

ModuleNotFoundError: No module named 'numpy'

In [13]:
import numpy as np

# Define matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Print the result
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#multiply : element wise matrix multiplication
#matmul   : matrix product of two arrays
#dot      : dot products of two arrays
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.multiply(arr1, arr2)
print(arr_result)

In [29]:
import numpy as np
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.matmul(arr1, arr2)

print(f'Matrix Product of arr1 and arr2 is:\n{arr_result}')



Matrix Product of arr1 and arr2 is:
[[19 22]
 [43 50]]


MATRIX DIVISION

In [14]:
import numpy as np

# Creating the matrices
a = np.array([[4, 6], [8, 10]])
b = np.array([[2, 3], [4, 5]])

# Dividing matrices
result = np.divide(a, b)

print(result)

[[2. 2.]
 [2. 2.]]


In [15]:
import numpy as np

# Creating the matrices
a = np.array([[4, 6], [8, 10]])
b = np.array([[2, 3]])

# Dividing matrices
result = np.divide(a, b)

print(result)

[[2.         2.        ]
 [4.         3.33333333]]


In [16]:
import numpy as np

# Creating the matrices
a = np.array([[4, 6], [8, 10]])
b = np.array([[2], [4]])

# Dividing matrices
result = np.divide(a, b)

print(result)

[[2.  3. ]
 [2.  2.5]]


SUBTRACTION

In [26]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise subtraction
result_matrix = matrix1 - matrix2
print("Result of Element-wise Subtraction:")
print(result_matrix)

Result of Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]


In [27]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2],
                   [3, 4]])

matrix2 = np.array([[5, 6],
                   [7, 8]])

# Perform matrix subtraction using np.subtract()
result_matrix = np.subtract(matrix1, matrix2)
print("Result of Matrix Subtraction using np.subtract():")
print(result_matrix)

Result of Matrix Subtraction using np.subtract():
[[-4 -4]
 [-4 -4]]


SCALAR MULTIPLICATION

In [17]:
# Define the scalar and the matrix
scalar = 5
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Perform scalar multiplication
result = [[scalar * element for element in row] for row in matrix]

# Print the result
for row in result:
    print(row)

[5, 10, 15]
[20, 25, 30]
[35, 40, 45]


In [18]:
# Define the scalar and the matrix
scalar = 3
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Perform scalar multiplication
result = []
for row in matrix:
    new_row = []
    for element in row:
        new_row.append(scalar * element)
    result.append(new_row)

# Print the result
for row in result:
    print(row)

[3, 6, 9]
[12, 15, 18]
[21, 24, 27]


MATRIX DETERMONANT

In [19]:
import numpy as np

# Define the matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

# Print the result
print("Determinant:", determinant)

Determinant: -2.0000000000000004


In [20]:
import numpy as np

# Define the matrix
matrix = np.array([[5, 2, 1], [1, -2, 0], [3, 4, 2]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

# Print the result
print("Determinant:", determinant)

Determinant: -13.999999999999996


VECTOR TRANSFORMATION

In [21]:
import numpy as np

# Define a 2D vector
vector = np.array([3, 4])

# Define a transformation matrix
matrix = np.array([[2, 0],
                   [0, 2]])

# Perform vector transformation
transformed_vector = np.dot(vector, matrix)

# Print the transformed vector
print(transformed_vector)

[6 8]


In [23]:
import numpy as np

# Define a 2D vector
vector = np.array([1, 2])

# Define a transformation matrix
matrix = np.array([[0, -1],
                   [1, 0]])

# Perform vector transformation
transformed_vector = np.dot(matrix, vector)

# Print the transformed vector
print(transformed_vector)

[-2  1]


REFERENCES
1.#https://www.digitalocean.com/community/tutorials/numpy-matrix-multiplication
2.#https://www.shecodes.io/athena#question-173226